version: '3.8'

services:
  traefik:
    image: traefik:latest
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      
  sonarqube:
      image: sonarqube
      restart: unless-stopped
      environment:
        - SONARQUBE_JDBC_USERNAME=sonarqube
        - SONARQUBE_JDBC_PASSWORD=/run/secrets/db_password
        - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonarqube
        - SONAR_WEB_CONTEXT=/sonarqube
      ports:
        - "9000:9000"
        - "9092:9092"
      secrets:
         - db_password
      labels:
        - "traefik.http.routers.sonarqube.rule=PathPrefix(`/sonarqube`)"
        - "traefik.http.routers.sonarqube.entrypoints=web"
        # - "traefik.http.services.sonarqube.loadbalancer.server.port=9000"
  db:
      image: postgres
      restart: unless-stopped
      environment:
        - POSTGRES_USER=sonarqube
        - POSTGRES_PASSWORD=/run/secrets/db_password
        - POSTGRES_DB=sonarqube
     # volumes:
     #   - sonarqube_db:/var/lib/postgresql
     #   - postgresql_data:/var/lib/postgresql/data
      secrets:
       - db_password
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "9411:9411"
      - "16686:16686"
      - "6831:6831/udp"
    labels:
      - "traefik.http.routers.jaeger.rule=Host(`jaeger.example.com`)"
      - "traefik.http.routers.jaeger.entrypoints=web"

volumes:
  sonarqube-db-data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
secrets:
  db_password:
    file: /tmp/db_password.txt
